# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/google-breakpad
name: Coverity Scan

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: find . -type f -iname "*" -exec chmod +x {} \;
    - name: install required packages
      run: sudo bash -c "MODE=regular ci/install.sh"
    - name: Configure
      run: ci/net-snmp-configure master
    - uses: vapier/coverity-scan-action@v1
      with:
        command: make
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
